-- Create the products table
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    category VARCHAR(100),
    items TEXT[], -- Array of strings to store items/ingredients
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS) on the table
-- This is a Supabase best practice to secure your data
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Policy 1: Allow everyone (public) to view the products
CREATE POLICY "Products are viewable by everyone" 
ON products FOR SELECT 
USING (true);

-- Policy 2: Allow authenticated users to insert new products
CREATE POLICY "Authenticated users can insert products" 
ON products FOR INSERT 
TO authenticated 
WITH CHECK (true);

-- Policy 3: Allow authenticated users to update products
CREATE POLICY "Authenticated users can update products" 
ON products FOR UPDATE 
TO authenticated 
USING (true);

-- Policy 4: Allow authenticated users to delete products
CREATE POLICY "Authenticated users can delete products" 
ON products FOR DELETE 
TO authenticated 
USING (true);
